# Generated by Django 3.2.9 on 2021-11-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20211127_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('tweets', models.ManyToManyField(blank=True, default=None, editable=False, related_name='hashtag', to='tweets.Tweet')),
            ],
        ),
    ]
